COMPONENT=fooAppC
CFLAGS += -I$(TOSDIR)/lib/printf
#BUILD_EXTRA_DEPS = RadioCountMsg.py RadioCountMsg.class
#CLEAN_EXTRA = RadioCountMsg.py RadioCountMsg.class RadioCountMsg.java

#RadioCountMsg.py: foo.h
#	mig python -target=$(PLATFORM) $(CFLAGS) -python-classname=RadioCountMsg foo.h radio_count_msg -o $@

#RadioCountMsg.class: RadioCountMsg.java
#	javac RadioCountMsg.java

#RadioCountMsg.java: foo.h
#	mig java -target=$(PLATFORM) $(CFLAGS) -java-classname=RadioCountMsg foo.h radio_count_msg -o $@


include $(MAKERULES) 
